name: $(BuildDefinitionName)_$(date:yyyyMMdd)$(rev:.r)

trigger: none

pr: none

variables:
  - name: backendServiceArm
    value: 'ashishcloud'
  - name: backendAzureRmResourceGroupName
    value: 'ashishcloud'
  - name: backendAzureRmStorageAccountName
    value: 'ashishtfstate'
  - name: backendAzureRmContainerName
    value: 'adovariableottf'
  - name: backendAzureRmKey
    value: 'terraform.tfstate'
  - name: environment
    value: 'production'

stages :
  - stage: terraform
    jobs:
    - job: validate
      continueOnError: false
      steps:
      - task: TerraformInstaller@0
        displayName: 'install'
        inputs:
          terraformVersion: '1.1.7'
      - task: TerraformTaskV2@2
        displayName: 'init'
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'ashishcloud'
          backendAzureRmResourceGroupName: '${{ variables.backendAzureRmResourceGroupName}}'
          backendAzureRmStorageAccountName: '${{ variables.backendAzureRmStorageAccountName}}'
          backendAzureRmContainerName: '${{ variables.backendAzureRmContainerName }}'
          backendAzureRmKey: 'terraform.tfstate'
          workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/'

      - task: TerraformTaskV2@2
        displayName: 'validate'
        inputs:
          provider: 'azurerm'
          command: 'validate'

      - task: TerraformTaskV2@2
        displayName: 'plan'
        inputs:
          provider: 'azurerm'
          command: 'plan'
          commandOptions: '-input=false -var-file="../terraform/environments/$(Environment)/$(Environment).tfvars"'
          environmentServiceNameAzureRM: 'ashishcloud'
          workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/'         
 
      # - task: TerraformTaskV2@2
      #   displayName: 'apply'
      #   inputs:
      #     provider: 'azurerm'
      #     command: 'apply'
      #     commandOptions: '-input=false -auto-approve -var-file="../$(Environment)/$(Environment).tfvars"'
      #     environmentServiceNameAzureRM: 'ashishcloud'
      #     workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/'